### ISSUE TITLE
Tests fail when using Seneca@1.x and 2.x

### ISSUE THREAD

**Issue by shanel262** [senecajs/seneca-basic#11]
Tests are failing when Seneca@1.4.0 is used with Node@5. I think there is a problem with the test.sh file.
https://travis-ci.org/senecajs/seneca-basic/builds/125596484

**Comment by shanel262** [comment]
It is now failing on both seneca@1.x and 2.x on all supported versions of node. https://travis-ci.org/senecajs/seneca-basic/builds/129072405

**Comment by mihaidma** [comment]
solved
